language: node_js

node_js:
- '0.8'
- '0.10'
- '0.11'

before_script:
- npm install -g grunt-cli

env:
  global:
  - secure: A4XL3VEm8jMg6wgTeD8V0Z4ajbQiOdHljAGboZlrnMm2NV4Eem6aFEiJkPK2QyxtyWjYFpA4Ec2LiXYWb3yLCrfyVQlM72dxUmf6Ho54Paf+41RaHnxkF1ijs3xCeW2oh4WneNiqrhl09Vnbr6CeZyzbcAvcKgxiqnAb80lqMI0=
  - secure: MuiKSmQCxp7swqpI9eRofth4Ty+ck08w+C+IomG9C5z6qbicRoZdxomm/uhu16eMzB2e0R9vjd1mVk2CGOQ92h5ozinjwG9KTyP0yCV0jMmkMGCG5sOT5z5Wk4POTb7LdX8xUeQ9ylMW6+phPtcTalIU2aDQIZvTYf8dmnaXmcM=
